sudo: false
language: csharp
solution: Source/CurrencyCloud.sln
before_install:
  - travis_retry nuget install NUnit.Runners -version 2.6.4
before_script:
  - nuget restore Source/CurrencyCloud.sln
after_script:
  - nunit-console Source/CurrencyCloud.Tests/bin/Release/CurrencyCloud.Tests.dll